### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by cpatmoore**
Add Apache License

### CODE REVIEW

**Comment by evolvedmicrobe** [comment]
@markjulmar @jamesmhogan

**Comment by evolvedmicrobe** [comment]
Note we used Apache 2.0 on the old site https://bio.codeplex.com/license

**Comment by cpatmoore** [comment]
This is Apache 2.0 License

**Comment by evolvedmicrobe** [comment]
@cpatmoore : Thanks! Only mentioned we used Apache 2.0 at the old site to inform others that this was the same license, didn't mean for it to come off as if this was different.

So, I'm still too much of an open source academic to care much about licenses (or spend time figuring them out... IP fights seems horribly distasteful to me), but I understand licenses are important in a lot of contexts, and I gather we have an open issue on this already.

This pull request solves these issues, which is great.  It is also a verbatim copy of our old license (with some trivial formatting differences, e.g. 1,2,3,4, subheadings become a,b,c,d subheadings, etc.).  All in all, I am not a lawyer but I can't think why this wouldn't be fit for a merge.

@jamesmhogan @markjulmar , if no objections, I will go ahead with the merge tomorrow.

**Comment by evolvedmicrobe** [comment]
Thanks @cpatmoore

**Pull request merged**
